name: glak

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: glak
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DOCKER_ENV=true
    networks:
      - genesis-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: glak-api
    command: node server.js
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - RESEND_API_KEY=${RESEND_API_KEY:-re_fxbYnt43_MAAExytzt2fHoExxH7ksT1Fc}
    networks:
      - genesis-network
    depends_on:
      - app

  nginx:
    image: nginx:alpine
    container_name: glak-nginx
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - genesis-network

networks:
  genesis-network:
    driver: bridge

